//
// EndPoints.swift
// CINET//  Pareto
//
//

import Foundation

struct EndPoint {
    static let kServerBase = "https://paredev.azurewebsites.net/"  
    static let sServerBase = "https://parestratdev.azurewebsites.net/"
    static let bServerBase = "https://backtestdev.azurewebsites.net/"
//    static let kServerBase = "http://localhost:8080/"
    static let signup = "signup"
    static let login = "login"
    static let account = "account/"
    static let otp = "verification/"
    static let forgotPassword = "forgot-password"
    static let changePassword = "recover-password"
    static let updateProfile = "v1/profile"
    static let updateAvatar = "v1/profile/avatar"
    static let countries = "v1/countries"
    static let states = "v1/countries/country_code/states"
    static let cities = "v1/countries/country_code/states/state_code/cities"
    static let magic = "magic"
    static let createLinkToken = "v1/plaid/create_link_token"
    static let setAccessToken = "v1/plaid/set_access_token"
    static let recipientBanks = "v1/plaid/recipient_banks"
    static let detachBank = "v1/plaid/recipient_banks/bank_id"
    static let Sign = "v1/account/sign"
    static let transfer = "v1/transfer"
    static let deposit = "v1/transfer/bank/bank_id/deposit"
    static let stats = "v1/account/stats"
    static let shareableLink = "v1/profile/shareable-link"
    static let Assests = "v1/assets"
    static let searchAsset = "v1/assets/single"
    static let watchlist = "v1/watchlist/single/{watchlist_id}"
    static let allWatchlists = "v1/watchlist/all"
    static let createWatchList = "v1/watchlist/create"
    static let deleteWatchlist = "v1/watchlist/{watchlist_id}"
    static let referel = "referral_code/verify/refCode"
    static let positions = "v1/positions"
    static let Order = "v1/orders"
    static let FavouriteAsset = "v1/watchlist/add"
    static let unFavoutite = "v1/watchlist/delete-asset/{watchlist_id}/{symbol}"
    static let Bars = "v1/market/stocks/{symbol}/bars"
    static let deepStock = "v1/market/stocks/{symbol}/all"
    static let singleStock = "v1/market/tickers/{symbol}"
    static let multiStock = "v1/market/tickers"
    static let topMovers = "v1/market/stocks/top-movers"
    static let news = "v1/market/stocks/news"
    static let allStrategies = "v1/strategy/all/user/{user_id}"
    static let strategies = "v1/strategy/all"
    static let strategyDetail = "v1/strategy/detail/{run_id}"
    static let startStrategy = "v1/strategy/manage_user"
    static let TradingView = "v1/account/trading-profile"
    static let ordrHistory = "v1/account/portfolio/history"
    static let termsCondition = kServerBase + "template/terms_conditions.html"
    static let orgIcon = kServerBase + "file/"
    static let runBacktest = "api/BacktestDev"
//    static let passwordPemKey = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDf6B5cnbTp6kNcgoPJomKr29ckK73Tw1AVIgTOzFnODs2WVFeZr81sPCjtHpEtORgqBg04M63BC2LWhu4Zshz+i7DqJ+7KSSOakCHQaFuiC3TxBy7h8g9T2krgKQfE5f6WhPugJdAR73jRtRGrhItyGIGMaih8e/G9/pWZB7nVcwIDAQAB"
    static let passwordPemKey = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCvRLr+lqDL6NTRhuFHCro2LO8QT/B98eUGS1H3agCsuY0U6XxSqfnFw2N0DxNm14YpEjAJjJJshMY3kUKXEIrvAEBPNYKlc6SXYPhyT1sjDgxdx0AbIgAHEZFFqRmDGaiLOjM1tTWxWu3sGeHCkTDdSYTIpGSekGgpAW1+2rIhQQIDAQAB"
}
